# Stamps XOR-obfuscated GitHub PAT into GitHubPlaytestEmbedded.Data.cs
# Usage (CI): PLAYTEST_LOGS_TOKEN=... pwsh BuildSupport/Stamp-GitHubPlaytestEmbedded.ps1
param(
    [string] $Token = $env:PLAYTEST_LOGS_TOKEN,
    [string] $ProjectRoot = (Get-Location).Path
)

$ErrorActionPreference = "Stop"
$dataPath = Join-Path $ProjectRoot "Assets/Game/Scripts/Runtime/Core/GitHubPlaytestEmbedded.Data.cs"
$supportDir = Join-Path $ProjectRoot "BuildSupport"
New-Item -ItemType Directory -Force -Path $supportDir | Out-Null

function Write-EmptyStub {
    $stub = @"
// <auto-generated>
// Empty stub committed to repo. CI overwrites before player build.
// </auto-generated>

namespace Game.Core
{
    internal static partial class GitHubPlaytestEmbedded
    {
        private static readonly byte[] Payload = System.Array.Empty<byte>();
        private static readonly byte[] Key = System.Array.Empty<byte>();
    }
}
"@
    [System.IO.File]::WriteAllText($dataPath, $stub)
}

$value = if ($null -eq $Token) { "" } else { "$Token".Trim() }
if ([string]::IsNullOrWhiteSpace($value)) {
    Write-Warning "PLAYTEST_LOGS_TOKEN is empty — writing empty embedded stub."
    Write-EmptyStub
    if (Test-Path (Join-Path $supportDir "github-playtest-token.txt")) {
        Remove-Item (Join-Path $supportDir "github-playtest-token.txt") -Force
    }
    exit 0
}

if (-not ($value.StartsWith("ghp_") -or $value.StartsWith("github_pat_") -or $value.StartsWith("gho_"))) {
    throw "PLAYTEST_LOGS_TOKEN must start with ghp_ / github_pat_ / gho_"
}

Set-Content -Path (Join-Path $supportDir "github-playtest-token.txt") -Value $value -NoNewline -Encoding utf8

$key = New-Object byte[] 32
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
try { $rng.GetBytes($key) } finally { $rng.Dispose() }

$plain = [System.Text.Encoding]::UTF8.GetBytes($value)
$payload = New-Object byte[] $plain.Length
for ($i = 0; $i -lt $plain.Length; $i++) {
    $payload[$i] = $plain[$i] -bxor $key[$i % $key.Length]
}

function Format-Bytes([byte[]] $bytes) {
    ($bytes | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
}

$payloadFormatted = Format-Bytes $payload
$keyFormatted = Format-Bytes $key

$source = @"
// <auto-generated>
// Stamped by CI/local build — do not edit by hand.
// </auto-generated>

namespace Game.Core
{
    internal static partial class GitHubPlaytestEmbedded
    {
        private static readonly byte[] Payload = { $payloadFormatted };
        private static readonly byte[] Key = { $keyFormatted };
    }
}
"@

[System.IO.File]::WriteAllText($dataPath, $source)
Write-Host "Stamped XOR-embedded GitHub playtest token → $dataPath (payloadLen=$($payload.Length))"
