# Stamps XOR-obfuscated Discord webhook into DiscordWebhookEmbedded.Data.cs
# Usage (CI): DISCORD_PLAYTEST_WEBHOOK_URL=... pwsh BuildSupport/Stamp-DiscordWebhookEmbedded.ps1
param(
    [string] $WebhookUrl = $env:DISCORD_PLAYTEST_WEBHOOK_URL,
    [string] $ProjectRoot = (Get-Location).Path
)

$ErrorActionPreference = "Stop"
$dataPath = Join-Path $ProjectRoot "Assets/Game/Scripts/Runtime/Core/DiscordWebhookEmbedded.Data.cs"
$supportDir = Join-Path $ProjectRoot "BuildSupport"
New-Item -ItemType Directory -Force -Path $supportDir | Out-Null

function Write-EmptyStub {
    $stub = @"
// <auto-generated>
// Empty stub committed to repo. CI overwrites before player build.
// </auto-generated>

namespace Game.Core
{
    internal static partial class DiscordWebhookEmbedded
    {
        private static readonly byte[] Payload = System.Array.Empty<byte>();
        private static readonly byte[] Key = System.Array.Empty<byte>();
    }
}
"@
    [System.IO.File]::WriteAllText($dataPath, $stub)
}

$url = if ($null -eq $WebhookUrl) { "" } else { "$WebhookUrl".Trim() }
if ([string]::IsNullOrWhiteSpace($url)) {
    Write-Warning "DISCORD_PLAYTEST_WEBHOOK_URL is empty — writing empty embedded stub."
    Write-EmptyStub
    if (Test-Path (Join-Path $supportDir "discord-webhook.url")) {
        Remove-Item (Join-Path $supportDir "discord-webhook.url") -Force
    }
    exit 0
}

if (-not $url.StartsWith("https://")) {
    throw "DISCORD_PLAYTEST_WEBHOOK_URL must start with https://"
}

Set-Content -Path (Join-Path $supportDir "discord-webhook.url") -Value $url -NoNewline -Encoding utf8

$key = New-Object byte[] 32
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
try { $rng.GetBytes($key) } finally { $rng.Dispose() }

$plain = [System.Text.Encoding]::UTF8.GetBytes($url)
$payload = New-Object byte[] $plain.Length
for ($i = 0; $i -lt $plain.Length; $i++) {
    $payload[$i] = $plain[$i] -bxor $key[$i % $key.Length]
}

function Format-Bytes([byte[]] $bytes) {
    ($bytes | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
}

$payloadFormatted = Format-Bytes $payload
$keyFormatted = Format-Bytes $key

$source = @"
// <auto-generated>
// Stamped by CI/local build — do not edit by hand.
// </auto-generated>

namespace Game.Core
{
    internal static partial class DiscordWebhookEmbedded
    {
        private static readonly byte[] Payload = { $payloadFormatted };
        private static readonly byte[] Key = { $keyFormatted };
    }
}
"@

[System.IO.File]::WriteAllText($dataPath, $source)
Write-Host "Stamped XOR-embedded Discord webhook → $dataPath (payloadLen=$($payload.Length))"
