using System;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace Game.Core
{
    /// <summary>
    /// CI stamps Discord webhook into BuildSupport, then a script embeds XOR'd bytes into
    /// <c>DiscordWebhookEmbedded.Data.cs</c> before Unity compiles the player.
    /// </summary>
    public static class DiscordWebhookStampRules
    {
        public const string CiWebhookFileRelativePath = "BuildSupport/discord-webhook.url";
        public const string EmbeddedDataRelativePath =
            "Assets/Game/Scripts/Runtime/Core/DiscordWebhookEmbedded.Data.cs";

        public static string Normalize(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
            {
                return null;
            }

            var trimmed = raw.Trim().Split('\n', '\r')[0].Trim();
            if (!trimmed.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            return trimmed;
        }

        public static string ResolveFromFileThenEnv(string projectRoot, string envValue)
        {
            if (!string.IsNullOrWhiteSpace(projectRoot))
            {
                var path = Path.Combine(projectRoot, CiWebhookFileRelativePath);
                if (File.Exists(path))
                {
                    var fromFile = Normalize(File.ReadAllText(path));
                    if (fromFile != null)
                    {
                        return fromFile;
                    }
                }
            }

            return Normalize(envValue);
        }

        public static byte[] CreateKey(int length = 32)
        {
            var key = new byte[Math.Max(8, length)];
            using var rng = RandomNumberGenerator.Create();
            rng.GetBytes(key);
            return key;
        }

        public static byte[] Xor(byte[] data, byte[] key)
        {
            if (data == null)
            {
                throw new ArgumentNullException(nameof(data));
            }

            if (key == null || key.Length == 0)
            {
                throw new ArgumentException("Key required.", nameof(key));
            }

            var result = new byte[data.Length];
            for (var i = 0; i < data.Length; i++)
            {
                result[i] = (byte)(data[i] ^ key[i % key.Length]);
            }

            return result;
        }

        public static string BuildEmbeddedDataSource(string webhookUrl, byte[] key)
        {
            var normalized = Normalize(webhookUrl)
                             ?? throw new ArgumentException("Invalid webhook URL.", nameof(webhookUrl));
            if (key == null || key.Length == 0)
            {
                throw new ArgumentException("Key required.", nameof(key));
            }

            var payload = Xor(Encoding.UTF8.GetBytes(normalized), key);
            var builder = new StringBuilder(payload.Length * 6 + 256);
            builder.AppendLine("// <auto-generated>")
                .AppendLine("// Stamped by CI/local build — do not edit by hand.")
                .AppendLine("// </auto-generated>")
                .AppendLine()
                .AppendLine("namespace Game.Core")
                .AppendLine("{")
                .AppendLine("    internal static partial class DiscordWebhookEmbedded")
                .AppendLine("    {")
                .Append("        private static readonly byte[] Payload = { ")
                .Append(FormatBytes(payload))
                .AppendLine(" };")
                .Append("        private static readonly byte[] Key = { ")
                .Append(FormatBytes(key))
                .AppendLine(" };")
                .AppendLine("    }")
                .AppendLine("}");
            return builder.ToString();
        }

        public static string BuildEmptyEmbeddedDataSource() =>
            @"// <auto-generated>
// Empty stub committed to repo. CI overwrites before player build.
// </auto-generated>

namespace Game.Core
{
    internal static partial class DiscordWebhookEmbedded
    {
        private static readonly byte[] Payload = System.Array.Empty<byte>();
        private static readonly byte[] Key = System.Array.Empty<byte>();
    }
}
";

        public static void WriteEmbeddedDataFile(string projectRoot, string webhookUrl)
        {
            var path = Path.Combine(projectRoot, EmbeddedDataRelativePath.Replace('/', Path.DirectorySeparatorChar));
            var source = string.IsNullOrEmpty(webhookUrl)
                ? BuildEmptyEmbeddedDataSource()
                : BuildEmbeddedDataSource(webhookUrl, CreateKey());
            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? projectRoot);
            File.WriteAllText(path, source, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }

        private static string FormatBytes(byte[] bytes)
        {
            var builder = new StringBuilder(bytes.Length * 6);
            for (var i = 0; i < bytes.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append("0x")
                    .Append(bytes[i].ToString("X2", CultureInfo.InvariantCulture));
            }

            return builder.ToString();
        }
    }
}
