// <auto-generated>
// Empty stub committed to repo. CI overwrites before player build.
// </auto-generated>

namespace Game.Core
{
    internal static partial class GitHubPlaytestEmbedded
    {
        private static readonly byte[] Payload = System.Array.Empty<byte>();
        private static readonly byte[] Key = System.Array.Empty<byte>();
    }
}
